// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/buiminhhoat/go-ecommerce-backend-api/internal/controller"
	"github.com/buiminhhoat/go-ecommerce-backend-api/internal/repositories"
	"github.com/buiminhhoat/go-ecommerce-backend-api/internal/service"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepository := repositories.NewUserRepository()
	iUserAuthRepository := repositories.NewUserAuthRepository()
	iUserService := service.NewUserService(iUserRepository, iUserAuthRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
